#+TITLE: EPQ personal audit
#+DATE: 17th August, 2021

* What do you do in your spare time?
Do programming, Play videogames, Call friends w/ discord
* What do you watch on youtube
Kurzgesagt, Tom Scott, 3Blue1Brown, Tantacrul: They're interesting
* Which instagram accounts do you follow
I don't use instagram, although when I did I followed mostly my friends
* What are your favorite things to watch on Netflix, TV, IPlayer, Prime
I do not have netflix or TV, I do not regularly watch anything on IPlayer or Prime. When I do, it's mostly films. I recently watched the matrix, and enjoyed it quite a lot.
* Which real or imaginary character do you identify with the most; why is this?
I don't really relate to any imaginary characters, and I'd feel pretty uncomfortable picking anyone real— except well— me! I say some pretty relatable stuff sometimes!
Alternatively we can say songs I relate to:
- "Home" by Cavetown
- "Three 'O clock things by AJR"
* What's your bucket list to complete by age 25?
I hope to grow my business, complete a few projects that I have not yet, and complete various personal processes such as changing my name
* Are there any good books you have read recently and is there a genre you like?
Yes! Thank you, this is a brilliant question! I really enjoy the Shardlake series of books. They're historical fiction, very well written, and exciting all the way through with twists to keep the reader interested. I'd say any of them. In terms of genre? I'd probably say I'm more interested in fiction than non-fiction, and I like fantasy, sci-fi, and sometimes historical fiction, although if I like a book depends more on how well-written it is.
In other book recommendations, I'd suggest The Fifth Science by Exurb1a. It's a collection of short sci-fi stories in the same universe and chronological order.
* How do you feel about sport?
I hate it: I was never good at it, so sport lessons became a barrage of being picked last, never being good enough, and consistently losing. I've enjoyed a few sports, including cycling, sailing, climbing and sometimes using the fitness suite at Chesterton, but I am not a sporty human.
* What sort of music do you like?
AJR is good, so is cavetown and porter robinson, I'm also currently listening to instrumental electronic music as I do this (on the Flow State podcast on spotify). My music tastes change over time and are fairly varied though, so I can't say that it'll always stay this way.
* Favorite song? Best Lyrics? Best album cover? Best music video?
** Favorite song?
Maybe 3 O clock things by AJR- Not sure about this one, there are a bunch of good choices
** Best lyrics?
Indecisive, could be something from cavetown, those sometimes end up being relatable, or something from AJR. In terms of lyrics that have helped me the most it'll be something from AJR or something from Porter Robinson; Porter's tracks definitely help me when I'm feeling down
** Best album cover?
I don't care about the album cover; I listen to albums on spotify with the window minimized or on the list of next up tracks most of the time. Album covers really don't matter to me.
** Best album? Extra bonus question:
Ok Orchestra by AJR or Nurture by Porter Robinson
** Best music video?
I care about music videos less than album covers; when I listen to music it is pretty much exclusively on spotify now, so I never get to see the music videos at all

Editor's note: I had forgotten about Ok Go, if you've never heard of them do yourself a favor and watch one of their music videos. I recommend Upside Down & Inside Out, but I cannot think of a video of theirs that isn't pretty incredible
* What would you go on a protest march in support of?
LGBTQ+ rights
* Any political events that have grabbed your attention?
How the pandemic is being handled and Biden pulling out of Afghanistan are the main ones
* How do you feel about artistic skills?
I make vector art sometimes, but I'm generally not particularly good at drawing or painting. I far prefer digital art where I can undo stuff and manipulate stuff just how I want it. I respect people who can make brilliant stuff without that tool, and people who make brilliant stuff through mediums such as digital drawing which I've never really gotten into
* How do you feel about crafts and DIY?
It's cool, again I don't do it much: I've done a bit of sewing in the past but not a whole lot. The closest I've done to woodwork was either making a viking longboat for school out of a dowel and a bottle in primary school or constructing my desk from Ikea
* How do you feel about working with digital media?
I like it in theory, I am not amazing at editing video (I've never found free software that I liked using very much), I have tried digitally creating music, and it didn't go amazingly, but that's partly due to not really understanding the topic well enough so I'm sure I could do better with some research on types of music. In terms of podcasts? I've considered starting one with friends sometimes, but realized that I didn't have amazing topics that I thought would be interesting as a podcast. My friends and I have conversations that are varied, not ones that fit into a specific format.
* What item of clothing you possess best represents you?
I'd say probably T-shirt, leggings or jeans, maybe a white hoodie if I feel so inclined

/Editor's note: I have since obtained a pink hoodie, and can conclusively say that $\text{pink hoodie} > \text{white hoodie}$. Also jeggings exist, so I don't have to split jeans and leggings. As I write this note I am wearing a pink hoodie, a white t-shirt & a pair of jeggings, and it is great/
* If you could learn anything, what would it be?
This question seems a little broad. I could say something like 'The solution to world hunger and the cure to cancer', or something like 'how artificial intelligence works', both of them would be things that I'd really really like to know, but one of them is a lot more possible than the other. I'm not sure what level of possibility we're talking about here. Given that it's the EPQ I'm answering this for, and the AI is in a subject that I'm more interested in working in, the others being purely theoretical things I'd like to learn to help people without having much of an interest in the process of getting there, I'm going to go with the AI
* What subjects are you studying at A-level?
Computer Science, Math, Further Math, Business Studies
* Is there anything you wish you could have taken at A-level but are not?
Some sort of Physics could have been cool, but being honest I'm fairly satisfied with my A-level choices. I wouldn't choose differently if given the same choice again.
* How do you relax?
I take a step back, stop doing work, stop looking at my messages, look away from my screen. Sometimes I take a walk. I find that if I don't, then I don't manage to take a proper break, and if I don't take a break for too long then my concentration dies
