
#+TITLE: Home

* Who am I?
Hi! I'm Skyler, a teenaged developer. I work with [[https://clicksminuteper.net][Clicks Minute Per]] to make discord bots & websites for fun, for money and because they're cool. We do development, designing & hosting in-house.

* What is the EPQ?
EPQ stands for /Extended Project Qualification/; it's an independent project worth half an a-level. It helps build skills such as time-management and research.

I'm taking the EPQ because my 6th form requires me to take it, however it also offers benefits in other areas and it can't be said that me taking the EPQ was entirely down to my 6th-form, I did choose to go here after all. The EPQ (as previously mentioned) helps develop various skills, people who've taken an EPQ tend to have higher grades overall and the EPQ also looks great on a personal statement or university application, with some universities even offering lower grade requirements if you get high EPQ grades. All-in-all it's a great opportunity for me.

* What am I doing for EPQ?
For my EPQ, I'm making a process management daemon. I [[file:Documents/process-manager-project-requirements.org][wrote a specification in year 11 for what this could look like]], which is what I'll be following as a rough guide. When the project is finished, I'll be taking it on to our production server and using it to run all of our bots, websites & other projects.

* All pages
- *Documents/*
  - [[file:Documents/poem-based-on-an-image.org][Just existing]] (Created on 2021-10-25 at 08:19:21)
  - [[file:Documents/project-progression-record.org][project-progression-record]] (Created on 2021-10-25 at 07:54:58)
  - [[file:Documents/questioning-a-co-owner.org][Doing research on what users would like to see]] (Created on 2021-10-24 at 19:50:17)
  - [[file:Documents/project-idea-mindmap.org][Mindmap of project ideas]] (Created on 2021-10-24 at 19:38:54)
  - [[file:Documents/process-manager-project-requirements.org][Project specification]] (Created on 2021-10-24 at 17:23:18)
  - [[file:Documents/why-this-project.org][Why have I chosen this project?]] (Created on 2021-10-19 at 21:33:19)
  - [[file:Documents/personal-audit.org][EPQ personal audit]] (Created on 2021-10-18 at 10:08:36)
- *Notes/*
  - [[file:Notes/20211024201928-upper_6th_meeting.org][Upper 6th Meeting]] (Created on 2021-10-24 at 19:33:54)
  - [[file:Notes/20211024202440-can_my_project_be_researched.org][Can my project be researched?]] (Created on 2021-10-24 at 19:31:01)
  - [[file:Notes/20211018105127-homepage.org][Notes]] (Created on 2021-10-24 at 15:43:46)
  - *Notes/daily/*
    - [[file:Notes/daily/2021-10-25.org][2021-10-25]] (Created on 2021-10-25 at 08:41:51)
    - [[file:Notes/daily/2021-10-24.org][2021-10-24]] (Created on 2021-10-25 at 07:26:46)
    - [[file:Notes/daily/2021-10-23.org][2021-10-23]] (Created on 2021-10-23 at 22:07:27)