:PROPERTIES:
:ID:       8d1867e7-3ec4-43a2-a4d1-5ba562ef7312
:END:
#+title: 2021-10-29
- [ ] Copy the PPR to documents
  - [ ] Get permission from OCR to publish PPR
  - [ ] Copy it over
- [X] Add a link back to the main page from each page on the site, as well as a link to the source on github
- [X] Create a schedule of when the EPQ will be done (2hrs/w to start with)
- [X] Create a kanban board (perhaps [[https://quire.io][quire]] to start with?, or [[https://github.com/Minion3665/EPQ/projects][github projects to better integrate with the existing systems]])
- [ ] Create a timeline of when stuff should be done by, or add time estimates to the kanban board

0:00:00 Alright, so overnight I thought of a way to add links to github, so I'm going to do that quickly & then start on the time-management tasks

0:03:10 I've done that, so I can mark that task as completed and start on the project-management side of things. I'm going to be using google calendar for scheduling as it's a calendar that I use for scheduling other things (such as all my lessons). I'm going to schedule 2 hours of work per week on the weekends, although I will undoubtedly use more time like that during the week in unscheduled time. 

0:17:03 [[https://calendar.google.com/calendar/u/0?cid=cWdiYjk1MXRsbXJnZDBzbTNubDFmOWU2N2NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][Here's a link to the calendar]]. Google took a while to create it, so while it was creating it I fixed the css for the header (making it wrap on smaller screens), next I'm going to create a kanban board using github projects (quire is nice, but using the same website for everything is nicer)

0:24:53 [[https://github.com/Minion3665/EPQ/projects/1][And here's a link to the kanban board]]. As a bonus, github issues will automatically be placed on the kanban board as well as having dated history. I'm therefore going to be using them instead of org agenda checkboxes (although I might still use the checkboxes for daily tasklists). I won't be adding past tasks to the kanban board, as there's no point, but I've added all present incomplete tasks to the board.
