:PROPERTIES:
:ID:       8d39261e-e994-45ef-a06e-8a72dea32fff
:END:
#+title: 2021-10-28 
* Today's task list
- [ ] Copy the PPR to documents
  - [ ] Get permission from OCR to publish PPR
  - [ ] Copy it over
- [X] Go to Moodle and look at the 'Examples of projects from Hills students'.
  - [X] Make notes on these examples
    - What are the strengths and weaknesses?
    - What can you learn from these?
    - How will this influence the way you work?
- [ ] Add a link back to the main page from each page on the site, as well as a link to the source on github

I still haven't recieved a reply from OCR, so I can't complete task 1, so I'm starting with the second task.

[[id:1bb811a3-54ac-43e5-a2d6-6463efa56211][Former project example analysis]] is stored in a separate note for easier access, please go there to see it.

As has become clear from doing the analysis, time management is an important part of the EPQ, so I'm therefore adding the following to my task list:
- [ ] Create a schedule of when the EPQ will be done (2hrs/w to start with)
- [ ] Create a kanban board (perhaps [[https://quire.io][quire]] to start with?, or [[https://github.com/Minion3665/EPQ/projects][github projects to better integrate with the existing systems]])
- [ ] Create a timeline of when stuff should be done by, or add time estimates to the kanban board

These tasks should hopefully help me to estimate how much time will need to be used for my EPQ and find where that time will come from.

As a second part of this, I need to record how much time I'm actually spending on my EPQ, so I'm going to start timing this, starting now. I'm going to be using the builtin [[https://orgmode.org/manual/Timers.html][timer functionality]] in orgmode (my note-taking program) to do this.

0:00:38 - Started work on task 3, adding links back to the main page & source code on each page
1:19:22 - I've added a link to the homepage and a link to the latest note. Unfortunately it doesn't look like it'll be possible to add links to git, as orgmode doesn't give a way to get the directory of the current file
