:PROPERTIES:
:ID:       4a250c3b-83f5-4dc9-bd09-4def6b3853d0
:END:
#+title: 2021-10-25
* Today's task list
- [X] Complete the page of the PPR (in your 'Planning' folder) up to the Mid Project Review.
- [X] License or get permission for all assets on the website
- [ ] Copy the PPR to documents
  - [ ] Get permission from OCR to publish PPR
  - [ ] Copy it over
- [ ] Templates should be created for daily diary notes
- [ ] Go to Moodle and look at the 'Examples of projects from Hills students'.
  - [ ] Make notes on these examples
    - What are the strengths and weaknesses?
    - What can you learn from these?
    - How will this influence the way you work?
      
Yesterday I completed a few of the tasks I wanted to, I got up to completing part of the PPR, so that's the first thing I'm going to be focusing on today.
---
I've now completed the PPR up until the stage where I have to (and emailed OCR for permission to publish it, as they hold the copyright to that document), and noticed that I haven't yet licensed the image in [[file:~/School/EPQ/Documents/poem-based-on-an-image.org][the poem I wrote based on the image]]... oops! My next task will be to get a license for that.

To do this, I reverse-image-searched the image using [[https://tineye.com/][tineye]], looking specifically for stock images. I then headed over to [[https://www.123rf.com][123rf]] and used their free trial (10 free stock images) in order to download the image under their standard license. I'm hoping that any more stock-image usage happens within the next month, as then I likely won't have to pay for licenses to any other stock images (credits don't roll over if you cancel your plan).

Finally, I downloaded a higher-resolution version of the image and put it onto the poem page.

All other assets on my website were created by me (excluding the voice recording, which also contains Pinea, I've already asked them for permission to publush this), so I don't need to get licenses to anything else right now. I will create a new task that I would like to
- [ ] Make a credits.org page displaying links to everything and everyone that's helped me in getting this project
I feel like this is an important addition, as I will rely on a lot of stuff in this project, and I want people to be adequately credited, cited & soforth.

I'm also going to add a further quality-of-life task:
- [ ] Add a link back to the main page from each page on the site, as well as a link to the source on github
