:PROPERTIES:
:ID:       90d6a4a6-48eb-4e4b-adc0-fad74c17f768
:END:
#+title: 2021-11-28
* A short note on what I did today
It's been a while since I did anything on my EPQ, and I have a time scheduled to work on the EPQ, so I worked on the EPQ today. I have a few more bits and pieces to research before I get the first leg of the project fully underway, so I decided to do research on [[id:3f64a1d4-b52d-4b7f-9a25-d2ebf1587810][what langauge to use]]. I decided to evaluate each of the languages on 4 general areas: popularity, experience, availablility of tools and libraries, and benchmarks of each language. After evaluating I would look at each of the lanaguages and decide which one to use based on the information I've gathered.

Insofar as I completed the research today python looks like a really strong choice, although it faltered a little on my future plans and I expect it to completely fail on the 'benchmarks' section of the research (I've run python and javascript benchmarks before; python is /not/ fast).
