:PROPERTIES:
:ID:       e9ae1c77-975b-42ce-a188-e05f125b9f73
:END:
#+title: 2021-10-27
* Today's task list
- [ ] Copy the PPR to documents
  - [ ] Get permission from OCR to publish PPR
  - [ ] Copy it over
- [X] Templates should be created for daily diary notes
- [ ] Go to Moodle and look at the 'Examples of projects from Hills students'.
  - [ ] Make notes on these examples
    - What are the strengths and weaknesses?
    - What can you learn from these?
    - How will this influence the way you work?
- [ ] Make a credits.org page displaying links to everything and everyone that's helped me in getting this project
- [ ] Add a link back to the main page from each page on the site, as well as a link to the source on github

As predicted, no tasks were done yesterday. Today I plan to start off by making a template for diary notes, as this is something I will need to do sooner or later (and sooner rather than later).

I've created 2 templates; a default (empty) one, and a template for diaries, here's what they look like!
* Diary entry
** What have I done since the last entry?
This is the first entry, over the course of the project so far I've:
- Decided on what my project is going to be
  - [[file:~/School/EPQ/Notes/20211024201928-upper_6th_meeting.org][Talked to upper 6ths about what makes a good project idea]]
  - Got information about what the project is
  - [[file:~/School/EPQ/Documents/project-idea-mindmap.org][Mindmapped what ideas would be good]]
- Set up this website
- Done a little research on docker & LXC (yet to be written up here)
- Done a little research on what people who will be using the project want, including [[file:~/School/EPQ/Documents/questioning-a-co-owner.org][asking a co-owner what they'd like to see in the completed project]]
** What have I learned & how?
- I now understand the EPQ better, and what will make it up, be graded & soforth
** What worked well?
- The (yet-to-be-written-up) research revealed a lot of stuff I didn't know about LXC, docker & containerd, and gave me some ideas of how something like my project could be implemented
** What would I do differently next time?
- I would record the upper 6th meeting so that I could get a transcript
- I would pre-plan the questions I was going to ask the co-owner so that I could ask more questions & get more valuable information
