:PROPERTIES:
:ID:       1bb811a3-54ac-43e5-a2d6-6463efa56211
:END:
#+title: Former project example analysis

[[https://moodle.hrsfc.ac.uk/mod/folder/view.php?id=1064][If you're in the hrsfc moodle, you'll be able to view the projects discussed by clicking on this link]]. Unfortunately if you're not then I won't be able to publish the projects as they are not my work & I have no contact with these students, no way to get contact with these students, and no desire to ask them for permission to publish their projects. Sorry about that.[fn:1]

For each project:
- What are the strengths and weaknesses?
- What can you learn from these?
- How will this influence the way you work?

* AR Ant poster
** What went well?
- They did quite a lot of primary research, which was really good 
** What could be better?
- The text-scaling is hard to read on the 'overall end project' page, more focus could have been given to the accessibility of the project PDF
- Some bits of text render over others in the PDF
** What can I learn?
- Making sure your project notes are readable is important; if people can't read your project they're not going to rate it very highly
- Primary research can be useful; remember people around you who have the skills and tools which you will be using
** How will this influence my project?
- I will proofread work to ensure that it is readable & accessible
- I know [[file:../Documents/questioning-a-co-owner.org][the people who will be using the project]], as well as someone who works at [[https://docker.com][docker]], so it'd be possible to ask them about what my project needs & what exists in docker to do some useful primary research
* Embroidered family tree
** What went well?
- Evaluates reliability of sources
- Says what weaknesses there are in the final project (gender bias)
** What could be better?
- Had to print out the family tree in sections & would have wasted paper on printing logos without screenshotting workaround; this shows a lack of planning in what website to use 
** What can I learn?
- It may be a good idea to plan what tools will be used based on what will need to be done with them
- Looking at weaknesses, both of sources and of the final project is an important part of evaluation
** How will this influence my project?
- I will attempt to evaluate reliability of sources, although it may not always be relevant to do so (for example documentation will almost always be 100% reliable). Benchmarking, on the other hand, may be easier to have reliability scores
- I will evaluate the tools, libraries etc. that I will be using based on their features and what I need them to do. An example of an evaluation for a tool is [[id:c83a9bd1-2a46-47f7-9cec-d5b42d473eb4][this, on why I'm using org-mode instead of notion]]
* Hydroponics
** What went well?
- Explanation at the start of what hydroponics is, as I didn't know what hydroponics was at the start this was useful
** What could be better?
- There were a lot of diary entries that were essentially empty, and it feels like it could have been condensed a little more in places
** What can I learn?
- Again, the effectiveness of the diary entries are really important. I saw another project that used color-coding on this, which really helped to make the important information more visible, and is something I'll probably be doing in my project
- Adding explanations for terms the reader does not understand may be important for my project
** How will this influence my project?
- I'll explain things that the average person would not understand, as I am aware that I have some specialist knowledge going in to making my project
* Computer game
** What went well?
- Demonstration video worked well as a presentation format, as it allowed explanation alongside an example of the project working
** What could be better?
- Didn't have a lot of time to iron out bugs (not very much time to tweak combat, walking animation glitches, general jankiness of pathfinding)
** What can I learn?
- Doing a large project can lead you to not have enough time to polish stuff well enough, scalability is important in project choice, as is polishing as you go along rather than implementing a lot and ultimately getting a worse result
** How will this influence my project?
- I'll incrementally add features in order of importance, polishing acceptably at each level rather than leaving that until the end
- My project would also work well with the format of a demonstration video, which I'll do at the end of the project
* Science animations
** What went well?
- Their 'evaluation of sources' page is really well-made, showing relevance and quality alongside sources is a great idea
- In general, the documentation that they've produced seels to be very high-quality
- Their time-tracking allowed them to see how far they were through their project and rectify initial issues with being behind
** What could be better?
- The initial idea of the project was too ambitious
** What can I learn?
- Scheduling time properly can be very important for proper project management
** How will this influence my project?
- I'll spend a lot more time on creating intuitive and useful documentation than I otherwise would have, and I'll look at what other students have done in their documentation for inspiration
- I'll put time-management processes and planning in from the start, [[id:8d39261e-e994-45ef-a06e-8a72dea32fff][adding them to today's task list]]. The suggested time on an EPQ is 2h/w, so I'll schedule that much to start with and evaluate how far I get with that, tweaking as needed

* Footnotes

[fn:1]You may still find this page to be useful in the 'what can I learn' and 'how will this influence my project' sections of each evaluation 
