:PROPERTIES:
:ID:       9941e505-65be-4fa0-9d2d-6dddc5c3fda1
:END:
#+title: Can my project be researched?
Initially I worried if my project could be researched. It's a development project, and I don't usually think of those as having a lot of research. They have design stages, a lot of development, a lot of debugging and testing, and then later maintenance, but I couldn't think of what the research could be.

I then realized that of course development projects /do/ have research, it's just been hiding in all the other steps. Here's a few things that need research in a development project:
- What language would be best to use (Exploring what libraries a language has, along with speed, extendability, update frequency, community size & other factors)
- What frameworks, libraries etc. would be best to use (Looking at the documentation for various options)
- How to implement solutions in a given language (Stack overflow or similar)

And that's only /after/ deciding to do the project. Before doing the project you may also need to research
- What existing solutions there are
- If your problem exists & needs solving
- What ways could you sidestep your problem
There's little point in making something that nobody needs or wants after all...

So I fully believe that my EPQ project /does/ need research, a lot of it. The difficult part, of course, will be noticing when I'm doing that research and documenting it.
