name: Publish to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Packages
        run: sudo snap install emacs --classic && sudo apt install git-restore-mtime

      - name: Build the site
        run: git restore-mtime && sudo chmod +x ./build-web.sh && ./build-web.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: Web-out
