
#+TITLE: Home

* Who am I?
Hi! I'm Skyler, a teenaged developer. I work with [[https://clicksminuteper.net][Clicks Minute Per]] to make discord bots & websites for fun, for money and because they're cool. We do development, designing & hosting in-house.

* What is the EPQ?
EPQ stands for /Extended Project Qualification/; it's an independent project worth half an a-level. It helps build skills such as time-management and research.

I'm taking the EPQ because my 6th form requires me to take it, however it also offers benefits in other areas and it can't be said that me taking the EPQ was entirely down to my 6th-form, I did choose to go here after all. The EPQ (as previously mentioned) helps develop various skills, people who've taken an EPQ tend to have higher grades overall and the EPQ also looks great on a personal statement or university application, with some universities even offering lower grade requirements if you get high EPQ grades. All-in-all it's a great opportunity for me.

* What am I doing for EPQ?
For my EPQ, I'm making a process management daemon. I [[file:Documents/process-manager-project-requirements.org][wrote a specification in year 11 for what this could look like]], which is what I'll be following as a rough guide. When the project is finished, I'll be taking it on to our production server and using it to run all of our bots, websites & other projects.

* All pages
- *Notes/*
  - [[file:Notes/20211018105127-homepage.org][Notes]] (Created at 2021-10-24)
  - *Notes/daily/*
    - [[file:Notes/daily/2021-10-24.org][2021-10-24]] (Created at 2021-10-24)
    - [[file:Notes/daily/2021-10-23.org][2021-10-23]] (Created at 2021-10-24)
- *Documents/*
  - [[file:Documents/process-manager-project-requirements.org][Project specification]] (Created at 2021-10-24)
  - [[file:Documents/poem-based-on-an-image.org][Just existing]] (Created at 2021-10-24)
  - [[file:Documents/why-this-project.org][Why have I chosen this project?]] (Created at 2021-10-19)
  - [[file:Documents/personal-audit.org][EPQ personal audit]] (Created at 2021-10-18)